version: "3"
services:
  app:
    stdin_open: true
    tty: true
    build: .
    container_name: api-boilerplate.app:v1
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15.3
    user: "root:root"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./db-data:/var/lib/postgresql/data"
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME} -schemas=public -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - "./migrations:/flyway/sql"
    depends_on:
      - db