name: GitHub Api Boilerplate CI/CD
run-name: GO API Boilerplate
on:
  [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run test
        run: cd src/ && go test -cover ./...
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
            registry: 220361521127.dkr.ecr.us-east-1.amazonaws.com
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and tag Docker image
        run: |
          docker build -t my-docker-image .
          docker tag go-api-boilerplate:latest 220361521127.dkr.ecr.us-east-1.amazonaws.com/go-api-boilerplate:latest
      - name: Push Docker image to AWS ECR
        run: |
          docker push 220361521127.dkr.ecr.us-east-1.amazonaws.com/go-api-boilerplate:latest